apiVersion: parameters.kubeblocks.io/v1alpha1
kind: ParametersDefinition
metadata:
  name: {{ include "clickhouse24.configParamsDefName" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  fileName: customized_config.xml
  # ConfigurationSchema that impose restrictions on engine parameter's rule
  parametersSchema:
    # top level mysql configuration type
    topLevelKey: ClickhouseParameter

    # schemaInJSON: auto generate from cue scripts
    # example: ../../pkg/configuration/testdata/mysql_openapi.json
    cue: |-
      {{- .Files.Get "configs/clickhouse-config-constraint.cue" | nindent 6 }}