apiVersion: parameters.kubeblocks.io/v1alpha1
kind: ParamConfigRenderer
metadata:
  name: {{ include "clickhouse24.pcrName" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  componentDef: {{ include "clickhouse24.cmpdName" . }}
  parametersDefs:
    - {{ include "clickhouse24.userParamsDefName" . }}
    - {{ include "clickhouse24.configParamsDefName" . }}

  configs:
    - name: config.xml
      fileFormatConfig:
        format: xml
      reRenderResourceTypes:
        - tls
    - name: user.xml
      fileFormatConfig:
        format: xml
    - name: 00_default_overrides.xml
      fileFormatConfig:
        format: xml
      reRenderResourceTypes:
        - hscale
        - shardingHVScale
        - tls
    - name: customized_config.xml
      fileFormatConfig:
        format: xml
