apiVersion: operations.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  name: etcd-horizontalscaling
  namespace: default
spec:
  # Specifies the name of the Cluster resource that this operation is targeting.
  clusterName: etcd-cluster
  type: HorizontalScaling
  # Lists HorizontalScaling objects, each specifying scaling requirements for a Component, including desired total replica counts, configurations for new instances, modifications for existing instances, and instance downscaling options
  horizontalScaling:
    # Specifies the name of the Component.
    # - etcd
  - componentName: etcd
    # Specifies the number of total replicas.
    scaleIn:
      instances:
        # need to define instances in cluster.yaml,
        # spec.componentSpecs.instances
        - name: etcd-0
          replicaChanges: 1