apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: clickhouse-sharding
  namespace: default
spec:
  terminationPolicy: Delete
  componentSpecs:
    - name: ch-keeper # create clickhouse keeper
      componentDef: clickhouse-keeper-24
      replicas: 1
      configs:
        - name: clickhouse-keeper-tpl
          externalManaged: true
      resources:
        limits:
          cpu: "1"
          memory: "2Gi"
        requests:
          cpu: "1"
          memory: "2Gi"
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
  shardings:
    - name: shard
      shards: 2 # with 2 shard
      template:
        name: clickhouse  # each shard is a clickhouse component, with 2 replicas
        componentDef: clickhouse-24
        replicas: 2
        configs:
          - name: clickhouse-tpl
            externalManaged: true
          - name: clickhouse-user-tpl
            externalManaged: true
          - name: clickhouse-client-tpl
            externalManaged: true
        systemAccounts:
          - name: admin # name of the system account
            secretRef:
              name: udf-shard-account-info
              namespace: default
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        volumeClaimTemplates:
          - name: data
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 20Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: udf-shard-account-info
  namespace: default
type: Opaque
data:
  password: cGFzc3dvcmQxMjM=  # 'password123' in base64