coordinator:
- cn1:
    agent_host: 10.0.7.16
    agent_port: 8003
    host: 10.0.7.16
    port: 5432
    role: primary
    work_dir: /home/gbase/data/coord/cn1
datanode:
- dn1:
  - dn1_1:
      agent_host: 10.0.7.16
      agent_port: 8005
      host: 10.0.7.16
      port: 15432
      role: primary
      work_dir: /home/gbase/data/dn1/dn1_1
  - dn1_2:
      agent_host: 10.0.7.17
      agent_port: 8006
      host: 10.0.7.17
      port: 15433
      role: standby
      work_dir: /home/gbase/data/dn1/dn1_2
  - dn1_3:
      agent_host: 10.0.7.18
      agent_port: 8007
      host: 10.0.7.18
      port: 15434
      role: standby
      work_dir: /home/gbase/data/dn1/dn1_3
- dn2:
  - dn2_1:
      agent_host: 10.0.7.16
      agent_port: 8008
      host: 10.0.7.16
      port: 20010
      role: primary
      work_dir: /home/gbase/data/dn2/dn2_1
  - dn2_2:
      agent_host: 10.0.7.17
      agent_port: 8009
      host: 10.0.7.17
      port: 20011
      role: standby
      work_dir: /home/gbase/data/dn2/dn2_2
  - dn2_3:
      agent_host: 10.0.7.18
      agent_port: 8010
      host: 10.0.7.18
      port: 20012
      role: standby
      work_dir: /home/gbase/data/dn2/dn2_3
dcs:
- host: 10.0.7.16
  port: 2379
- host: 10.0.7.17
  port: 2379
- host: 10.0.7.18
  port: 2379
env:
  cluster_type: multiple-nodes
  pkg_path: /home/gbase/gbase_package
  port: 22
  prefix: /home/gbase/gbase_db
  third_ssh: false
  user: gbase
  version: V5_S3.0.0B114
gha_server:
- gha_server1:
    host: 10.0.7.16
    port: 20001
gtm:
- gtm1:
    agent_host: 10.0.7.16
    agent_port: 8001
    host: 10.0.7.16
    port: 6666
    role: primary
    work_dir: /home/gbase/data/gtm/gtm1
