# Default values for gbase addon
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  registry: apecloud-registry.cn-zhangjiakou.cr.aliyuncs.com
  gbase:
    repository:  apecloud/gbase8c_ha
    pullPolicy: IfNotPresent
    tag: "5.5"
  exporter: 
    repository:  apecloud/gbase-exporter
    pullPolicy: IfNotPresent
    tag: latest

gbaseConfigs:
  dataMountPath: /data
  service: 
    port: 15400

metrics:
  service:
    port: 9187

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""
clusterVersionOverride: ""

roleProbe:
  periodSeconds: 30
  initialDelaySeconds: 10
  timeoutSeconds: 10

resourceNamePrefix: ""
