apiVersion: apps.kubeblocks.io/v1
kind: ComponentVersion
metadata:
  name: apecloud-mysql
  labels:
    {{- include "apecloud-mysql.labels" . | nindent 4 }}
spec:
  releases:
  - name: apecloud-mysql-8.0.30
    serviceVersion: "8.0.30"
    images:
      init-data: {{ .Values.image.registry | default "docker.io" }}/apecloud/mysql_audit_log:8.0.33
      mysql: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:8.0.30-5.beta3.20240330.g94d1caf.15
      mysql-exporter: {{ .Values.metrics.image.registry | default ( .Values.image.registry | default "docker.io" ) }}/{{ .Values.metrics.image.repository }}:{{ default .Values.metrics.image.tag }}
  compatibilityRules:
  - releases: [apecloud-mysql-8.0.30]
    compDefs: [apecloud-mysql]
