apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: {{ include "kblib.clusterName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "kblib.clusterLabels" . | nindent 4 }}
spec:
  terminationPolicy: {{ .Values.terminationPolicy }}
  configs:
    - name: orioledb-configuration
      externalManaged: true
  {{- include "orioledb-cluster.componentSpec" . }}