apiVersion: v2
name: wesql
description: WeSQL is an innovative MySQL distribution that adopts a compute-storage separation architecture,
  with storage backed by S3 (and S3-compatible systems). It can run on any cloud, ensuring no vendor lock-in.

type: application

version: 0.9.0

appVersion: "8.0.35-0.1.0_beta3.38"

home: https://wesql.io/
icon: https://wesql.io/img/logo.png

maintainers:
  - name: free6om
    url: https://github.com/free6om

sources:
- https://github.com/wesql/wesql/

annotations:
  addon.kubeblocks.io/kubeblocks-version: ">=0.9.0"
  addon.kubeblocks.io/model: "RDBMS"
  addon.kubeblocks.io/provider: "community"
