## @param nameOverride Override the app name
nameOverride: ""

## @param fullnameOverride Override the full app name
fullnameOverride: ""

## @param terminationPolicy Define Cluster termination policy. One of DoNotTerminate, Halt, Delete, WipeOut.
terminationPolicy: Delete

## @param tolerations Define global Tolerations for the cluster all pod's assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

## @param affinity Affinity setting for etcd cluster pods assignment
affinity: {}

## @param replicas Number of replicas for the etcd cluster
replicas: 3

## Service configurations
## set service name to enable peerService and clientService

## @param peerService.enabled Enable peerService (no need to enable for single cluster)
peerService:
  enabled: false
  ## @param peerService.type Service type for etcd peers, default peer service for single cluster use headless ClusterIP, valid option is LoadBalancer, will support NodePort in the future.
  type: LoadBalancer
  ## @param peerService.annotations Optional, if peerService type is LoadBalancer, you may need to specify annotations for Cloud Provider
  annotations: {}

## clientService is the configuration for etcd client communication
clientService:
  name: ""
  ## @param clientService.type etcd service type, valid options are ExternalName, ClusterIP, NodePort, and LoadBalancer.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  port: 2379
  role: leader
  ## @param clientService.nodePort Optional, if clientService type is NodePort, by default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
  nodePort:
  ## @param clientService.annotations Optional, if clientService type is LoadBalancer, you may need to specify annotations for Cloud Provider
  annotations: {}

## @param cpu CPU resource request for each etcd pod
cpu: 0.5
## @param memory Memory resource request for each etcd pod, the unit is Gi
memory: 0.5
## @param storage Storage size for each etcd pod, the unit is Gi
storage: 10

## @param requests.cpu If not set, use cpu
## @param requests.memory If not set, use memory
# requests:
#   cpu: 100m
#   memory: 128Mi

## @param persistence using Persistent Volume Claims
persistence: true
## @param storageClassName, storage class name
storageClassName:

## @param tlsEnable Enable TLS for etcd cluster
tlsEnable: false

## Customized default values to override kblib chart's values
extra:
  disableExporter: false
