apiVersion: apps.kubeblocks.io/v1alpha1
kind: ClusterDefinition
metadata:
  name: redis
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  topologies:
    - name: standalone
      components:
        - name: redis
          compDef: {{ include "redis.componentDefNameRegexPattern" . }}
      default: true
    - name: replication
      components:
        - name: redis
          compDef: {{ include "redis.componentDefNameRegexPattern" . }}
        - name: redis-sentinel
          compDef: {{ include "redis-sentinel.componentDefNameRegexPattern" . }}
      orders:
        provision:
          - redis-sentinel
          - redis
        terminate:
          - redis-sentinel
          - redis
        update:
          - redis-sentinel
          - redis
    - name: replication-twemproxy
      components:
        - name: redis
          compDef: {{ include "redis.componentDefNameRegexPattern" . }}
        - name: redis-sentinel
          compDef: {{ include "redis-sentinel.componentDefNameRegexPattern" . }}
        - name: redis-twemproxy
          compDef: {{ include "redis-twemproxy.componentDefNameRegexPattern" . }}
      orders:
        provision:
          - redis-sentinel
          - redis
          - redis-twemproxy
        terminate:
          - redis-twemproxy
          - redis-sentinel
          - redis
        update:
          - redis-sentinel
          - redis-twemproxy
          - redis