apiVersion: v2
name: rabbitmq
description: RabbitMQ is a reliable and mature messaging and streaming broker.

type: application

version: 1.0.0-alpha.0

appVersion: "3.13.2"

# Add a dependency to the kubeblocks definition library chart
dependencies:
  - name: kblib
    version: 0.1.0
    repository: file://../kblib
    alias: extra

home: https://www.rabbitmq.com/
icon: https://www.rabbitmq.com/img/rabbitmq-logo-with-name.svg
keywords:
  - rabbitmq
  - database
  - message
  - broker

maintainers:
  - name: xuriwuyun
    url: https://github.com/apecloud/kubeblocks/deploy

annotations:
  addon.kubeblocks.io/kubeblocks-version: ">=0.9.0"
  addon.kubeblocks.io/model: "message"
  addon.kubeblocks.io/provider: "community"
