apiVersion: apps.kubeblocks.io/v1alpha1
kind: ClusterDefinition
metadata:
  name: {{ include "gbase.clusterDefName" . }}
  labels:
    {{- include "gbase.labels" . | nindent 4 }}
spec:
  topologies:
  - name: distribution
    components:
    - name: gbase-gha-server
      compDef: {{ include "gbase.componentDefName" . }}-gha-server
    - name: gbase-dcs
      compDef: {{ include "gbase.componentDefName" . }}-dcs
    - name: gbase-datanode
      compDef: {{ include "gbase.componentDefName" . }}-datanode
    - name: gbase-gtm
      compDef: {{ include "gbase.componentDefName" . }}-gtm
    - name: gbase-gha-coord
      compDef: {{ include "gbase.componentDefName" . }}-coordinator
  - name: replication
    default: true
    components:
    - name: gbase-single
      compDef: {{ include "gbase.componentDefName" . }}-single
