apiVersion: apps.kubeblocks.io/v1alpha1
kind: ClusterDefinition
metadata:
  name: {{ include "gbase.clusterDefName" . }}
  labels:
    {{- include "gbase.labels" . | nindent 4 }}
spec:
  topologies:
  - name: distribution
    components:
    - name: gbase-datanode
      compDef: {{ include "gbase.componentDefName" . }}-datanode
  
  - name: replication
    default: true
    components:
    - name: gbase-single
      compDef: {{ include "gbase.componentDefName" . }}-single
