apiVersion: apps.kubeblocks.io/v1alpha1
kind: ComponentDefinition
metadata:
  name: {{ include "gbase.componentDefName" . }}
  labels:
    {{- include "gbase.labels" . | nindent 4 }}
spec:
  provider: kubeblocks.io
  description: gabse 8c 
  serviceKind: gbase
  serviceVersion: 5.0.0
  configs:
    - name: gbase-config
      templateRef: {{ include "gbase.cmConfigName" . }}
      namespace: {{ .Release.Namespace }}
      volumeName: gbase-config
      defaultMode: 0444
  scripts:
    - name: gbase-scripts
      templateRef: {{ include "gbase.cmScriptsName" . }}
      namespace: {{ .Release.Namespace }}
      volumeName: scripts
      defaultMode: 0555 
  runtime:
    containers:
      - name: gbase
        imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
        command: ["/usr/sbin/init"]
        lifecycle:
          postStart:
            exec:
              command: ["/scripts/start_cluster.sh"]
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
          - mountPath: /config
            name: gbase-config
          - mountPath: /data
            name: data
          - name: scripts
            mountPath: /scripts