apiVersion: apps.kubeblocks.io/v1alpha1
kind: ComponentDefinition
metadata:
  name: {{ include "gbase.componentDefName" . }}-gha-server
  labels:
    {{- include "gbase.labels" . | nindent 4 }}
spec:
  provider: kubeblocks.io
  description: gabse 8c gha-server node
  serviceKind: gbase
  serviceVersion: 5.0.0
  configs:
    - name: gbase-config
      templateRef: {{ include "gbase.cmConfigName" . }}
      namespace: {{ .Release.Namespace }}
      volumeName: gbase-config
      defaultMode: 0444
  scripts:
    - name: gbase-scripts
      templateRef: {{ include "gbase.cmScriptsName" . }}
      namespace: {{ .Release.Namespace }}
      volumeName: scripts
      defaultMode: 0555 
  systemAccounts:
    - name: gbase
      initAccount: true
      passwordGenerationPolicy:
        length: 16
        numDigits: 8
        numSymbols: 0
        letterCase: MixedCases
  vars:
    - name: GBASE_USER
      valueFrom:
        credentialVarRef:
          compDef: {{ include "gbase.componentDefName" . }}-gha-server
          name: gbase
          optional: false
          username: Required
    - name: GBASE_PASSWORD
      valueFrom:
        credentialVarRef:
          compDef: {{ include "gbase.componentDefName" . }}-gha-server
          name: gbase
          optional: false
          password: Required   
    - name: GBASE_GTM_HEADLESS
      valueFrom:
        serviceVarRef:
          compDef: {{ include "gbase.componentDefName" . }}-gtm
          name: headless
          optional: true
          host: Optional
    - name: GBASE_DATANODE_HEADLESS
      valueFrom:
        serviceVarRef:
          compDef: {{ include "gbase.componentDefName" . }}-datanode
          name: headless
          optional: true
          host: Optional
    - name: GBASE_COORDINATOR_HEADLESS
      valueFrom:
        serviceVarRef:
          compDef: {{ include "gbase.componentDefName" . }}-coordinator
          name: headless
          optional: true
          host: Optional
    - name: GBASE_DCS_HEADLESS
      valueFrom:
        serviceVarRef:
          compDef: {{ include "gbase.componentDefName" . }}-dcs
          name: headless
          optional: true
          host: Optional
    - name: GBASE_GHA_SERVER_HEADLESS
      valueFrom:
        serviceVarRef:
          compDef: {{ include "gbase.componentDefName" . }}-gha_server
          name: headless
          optional: true
          host: Optional
    - name: GBASE_GTM_POD_LIST
      valueFrom:
        componentVarRef:
          compDef:  {{ include "gbase.componentDefName" . }}-gtm
          optional: true
          instanceNames: Optional
    - name: GBASE_DATANODE_POD_LIST
      valueFrom:
        componentVarRef:
          compDef: {{ include "gbase.componentDefName" . }}-datanode
          optional: true
          instanceNames: Optional
    - name: GBASE_COORDINATOR_POD_LIST
      valueFrom:
        componentVarRef:
          compDef: {{ include "gbase.componentDefName" . }}-coordinator
          optional: true
          instanceNames: Optional
    - name: GBASE_DCS_POD_LIST
      valueFrom:
        componentVarRef:
          compDef: {{ include "gbase.componentDefName" . }}-dcs
          optional: true
          instanceNames: Optional
    - name: GBASE_GHA_SERVER_POD_LIST
      valueFrom:
        componentVarRef:
          compDef: {{ include "gbase.componentDefName" . }}-gha_server
          optional: true
          instanceNames: Optional  
  updateStrategy: Parallel
  podManagementPolicy: Parallel
  runtime:
    nodeSelector:
      gbase: "true"
    containers:
      - name: gbase
        imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
        command: ["/usr/sbin/init"]
        ports:
          - name: gbase-dataport
            containerPort: {{ .Values.gbaseConfigs.service.port }}
        lifecycle:
          postStart:
            exec:
              command: ["/scripts/node_setup.sh"]
        securityContext:
          privileged: true
          runAsUser: 0
        env:
          - name : server_port
            value: "5432"
        volumeMounts:
          - mountPath: /config
            name: gbase-config
          - mountPath: /data
            name: data
          - name: scripts
            mountPath: /scripts
          - name: ssh-key
            mountPath: /ssh-key
            readOnly: true
    volumes:
    - name: ssh-key
      secret:
        secretName: gbase-ssh-rsa-secret
