apiVersion: apps.kubeblocks.io/v1alpha1
kind: ComponentVersion
metadata:
  name: gbase
  labels:
    {{- include "gbase.labels" . | nindent 4 }}
spec:
  releases:
  - name: gbase-5.0.0
    serviceVersion: "5.0.0"
    images:
      gbase: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.gbase.repository }}:{{ .Values.image.gbase.tag }} 
  - name: gbase-ps-5.0.0
    serviceVersion: "5.0.0"
    images:   
      gbase: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.gbase.repository }}:{{ .Values.image.gbase.tag }} 
      exporter: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.exporter.repository }}:{{ .Values.image.exporter.tag }} 
  compatibilityRules:
  - releases: [gbase-5.0.0]
    compDefs: 
      - {{ include "gbase.componentDefName" . }}-gha-server
      - {{ include "gbase.componentDefName" . }}-gtm
      - {{ include "gbase.componentDefName" . }}-dcs
      - {{ include "gbase.componentDefName" . }}-datanode
      - {{ include "gbase.componentDefName" . }}-coordinator
      - {{ include "gbase.componentDefName" . }}-ha
  - releases: [gbase-ps-5.0.0]
    compDefs: 
      - {{ include "gbase.componentDefName" . }}-ha
