# Default values for oceanbase-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


nameOverride: ""
fullnameOverride: ""
clusterVersionOverride: "4.2.0.0-100010032023083021"

# how many clusters to create with-in one ob cluster, set to 2 when creating a primary and secondary oceanbae cluster
obClusters: 2
# zone count
zoneCount: 1
# replicas, it should be larger than zoneCount
replicas: 1

tenant:
  name: "alice"
  max_cpu: 1
  memory_size: 2
  log_disk_size: 5

# resources
cpu: 4
memory: 4
datafile: 30
datalog: 30
log: 10

storageClassName: ""

# customized default values to override kblib chart's values
# extra:
#   podAntiAffinity: Required
#   availabilityPolicy: node
#   tenancy: DedicatedNode

debug: false
hostnetwork: "enabled"

proxy:
  enabled: "enabled"
  configserver:
    replicas: 1
    cpu: 1
    memory: 1
  obproxy:
    replicas: 1
    cpu: 1
    memory: 1
