## cluster settings for gbase
version: latest
storageClassName: ""

## @param mode gbase cluster topology mode, distribution or HA. 
## distribution now is no functional
mode: HA

sshKeySecret: gbase-ssh-rsa-secret

clusterVersionOverride: "gbase8c-5.0.0"

replication:
  replicas: 2 # single or replication
  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "1"
      memory: "4Gi"
  dataStorage: "20Gi"