## cluster settings for neon
version: latest
storageClassName: ""


terminationPolicy: Delete

useLegacyCompDef: false

clusterVersionOverride: "gbase8c-5.0.0"

gbase:
  replicas: 1
  resources:
    requests:
      cpu: "1000m"
      memory: "4Gi"
    limits:
      cpu: "1"
      memory: "8Gi"
  dataStorage: "40Gi"
