apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: surreal-cluster
  namespace: demo
spec:
  clusterDefinitionRef: surrealdb-1.0.0
  topology: surreal-memory
  terminationPolicy: Delete
  componentSpecs:
    - name: surreal
      serviceVersion: 2.2.1
      env:
        - name: SURREAL_USER
          value: root
        - name: SURREAL_PASS
          value: surreal
      replicas: 1
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 500m
          memory: 512Mi