apiVersion: apps.kubeblocks.io/v1
kind: ComponentDefinition
metadata:
  name: etcd
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
  annotations:
    {{- include "etcd.annotations" . | nindent 4 }}
spec:
  provider: ApeCloud
  description: {{ .Chart.Description }}
  serviceKind: {{ .Chart.Name }}
  serviceVersion: {{ .Chart.AppVersion }}
  runtime:
    initContainers:
      - name: inject-shell
        imagePullPolicy: {{default .Values.busyboxImage.pullPolicy "IfNotPresent"}}
        volumeMounts:
          - name: shell
            mountPath: /shell
        command:
          - bin/sh
          - -c
          - scripts/inject-shell.sh
    containers:
      - name: etcd
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: CURRENT_POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
        ports:
          - containerPort: 2379
            name: client
          - containerPort: 2380
            name: peer
        volumeMounts:
          - name: data
            mountPath: {{ .Values.dataMountPath }}
          - name: config
            mountPath: /etc/etcd
          - name: scripts
            mountPath: /scripts
          - name: shell
            mountPath: /shell
        command:
          - /shell/sh
          - -c
          - |
            export PATH=$PATH:/shell
            # for convenient to use the same entrypoint
            if [ ! -e /bin/sh ]; then
              cp /shell/sh /bin
            fi
            /scripts/start.sh
    volumes:
      - name: shell
        emptyDir: {}
  vars:
    - name: ETCD_VERSION
      value: {{ .Chart.AppVersion }}
    - name: DATA_DIR
      value: {{ .Values.dataDir }}
    - name: CLUSTER_NAME
      valueFrom:
        clusterVarRef:
          clusterName: Required
    - name: TLS_MOUNT_PATH
      value: {{ .Values.tlsMountPath }}
    - name: CLIENT_TLS
      value: "{{ .Values.tls.client }}"
    - name: PEER_TLS
      value: "{{ .Values.tls.peer }}"
    - name: TMP_CONFIG_PATH
      value: {{ .Values.tmpConfigPath }}
    - name: PEER_FQDNS
      valueFrom:
        componentVarRef:
          optional: false
          podFQDNs: Required
    - name: PEER_ENDPOINT
      valueFrom:
        serviceVarRef:
          optional: true
          host: Required
          loadBalancer: Required
    - name: LEADER_POD_FQDN
      valueFrom:
        componentVarRef:
          optional: false
          podFQDNsForRole:
            role: leader
            option: Required
  volumes:
    - name: data
      needSnapshot: true
  services:
    - name: peer
      spec:
        ports:
          - name: peer
            port: 2380
            targetPort: peer
      podService: true
      disableAutoProvision: true
  # reference: https://etcd.io/docs/v3.5/op-guide/runtime-configuration/ single member changes is better
  updateStrategy: Serial
  roles:
    - name: leader
      serviceable: true
      writable: true
      votable: true
    - name: follower
      serviceable: true
      writable: false
      votable: true
  lifecycleActions:
    roleProbe:
      exec:
        image: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:{{ .Values.image.tag.major3.minor5.patch6 }}
        command:
          - /bin/sh
          - -c
          - scripts/role-probe-script.sh
    memberJoin:
      exec:
        image: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:{{ .Values.image.tag.major3.minor5.patch6 }}
        command:
          - /bin/sh
          - -c
          - scripts/etcd-member-leave.sh
    memberLeave:
      exec:
        image: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:{{ .Values.image.tag.major3.minor5.patch6 }}
        command:
          - /bin/sh
          - -c
          - scripts/etcd-member-leave.sh
    switchover:
      exec:
        image: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:{{ .Values.image.tag.major3.minor5.patch6 }}
        command:
          - /bin/sh
          - -c
          - scripts/switchover.sh
  configs:
    - name: etcd-configuration-tpl
      templateRef: {{ include "etcd.configTplName" .}}
      constraintRef: {{ include "etcd.configConstraintName" .}}
      namespace: {{ .Release.Namespace }}
      volumeName: config
      defaultMode: 0666
      reRenderResourceTypes:
        - hscale
    - name: etcd-scripts
      templateRef: {{ include "etcd.cmScriptsName" .}}
      namespace: {{ .Release.Namespace }}
      volumeName: scripts
      defaultMode: 0555
  exporter:
    containerName: etcd
    scrapePort: "2379"
    scrapePath: /metrics
    scrapeScheme: http
