apiVersion: apps.kubeblocks.io/v1
kind: ComponentVersion
metadata:
  name: etcd
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
spec:
  compatibilityRules:
    - compDefs: [etcd]
      releases: [v3.5.6, v3.5.15]
  releases:
    - name: v3.5.6
      serviceVersion: v3.5.6
      images:
        inject-brinaries: {{ .Values.busyboxImage.registry | default "docker.io" }}/{{ .Values.busyboxImage.repository }}:{{ default .Values.busyboxImage.tag }}
        inject-bash: {{ .Values.bashImage.registry | default "docker.io" }}/{{ .Values.bashImage.repository }}:{{ default .Values.bashImage.tag }}
        etcd: {{ .Values.image.registry | default "gcr.io" }}/{{ .Values.image.repository | default "etcd-development/etcd"}}:v3.5.6
    - name: v3.5.15
      serviceVersion: v3.5.15
      images:
        inject-brinaries: {{ .Values.busyboxImage.registry | default "docker.io" }}/{{ .Values.busyboxImage.repository }}:{{ default .Values.busyboxImage.tag }}
        inject-bash: {{ .Values.bashImage.registry | default "docker.io" }}/{{ .Values.bashImage.repository }}:{{ default .Values.bashImage.tag }}
        etcd: {{ .Values.image.registry | default "gcr.io" }}/{{ .Values.image.repository | default "etcd-development/etcd"}}:v3.5.15