apiVersion: apps.kubeblocks.io/v1
kind: ComponentVersion
metadata:
  name: etcd
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
spec:
  compatibilityRules:
    - compDefs:
        - {{ include "etcd.cmpdRegexpPattern" .}}
      releases:
        - 3.5.6
        - 3.5.15
  releases:
    - name: 3.5.6
      serviceVersion: 3.5.6
      images:
        inject-bash: {{ .Values.debianImage.registry | default "docker.io" }}/{{ .Values.debianImage.repository }}:{{ default .Values.debianImage.tag }}
        etcd: {{ .Values.image.registry | default "gcr.io" }}/{{ .Values.image.repository | default "etcd-development/etcd"}}:v3.5.6
    - name: 3.5.15
      serviceVersion: 3.5.15
      images:
        inject-bash: {{ .Values.debianImage.registry | default "docker.io" }}/{{ .Values.debianImage.repository }}:{{ default .Values.debianImage.tag }}
        etcd: {{ .Values.image.registry | default "gcr.io" }}/{{ .Values.image.repository | default "etcd-development/etcd"}}:v3.5.15