# Default values for minio cluster
# This is a YAML-formatted file
# Declare variables to be passed into your templates

replicas: 2

buckets: ""
user: ""
password: ""

#resources
cpu: 1
memory: 1
storageClassName: ""
storage: 20