---
{{- $vttabletcc := .Files.Get "config/mysql-scale-vttablet-config-effect-scope.yaml" | fromYaml }}
apiVersion: apps.kubeblocks.io/v1beta1
kind: ConfigConstraint
metadata:
  name: {{ include "apecloud-mysql.configConstraintVttabletName" . }}

  labels:
    {{- include "apecloud-mysql.labels" . | nindent 4 }}
spec:
  reloadAction:
    autoTrigger:
      processName: vttablet

  parametersSchema:
    topLevelKey: VtTabletParameter
    cue: |-
      {{- .Files.Get "config/mysql-scale-vttablet-config-constraint.cue" | nindent 6 }}

  ## define static parameter list
  {{- if hasKey $vttabletcc "staticParameters" }}
  staticParameters:
    {{- $params := get $vttabletcc "staticParameters" }}
    {{- range $params }}
    - {{ . }}
    {{- end }}
  {{- end}}

      ## define dynamic parameter list
  {{- if hasKey $vttabletcc "dynamicParameters" }}
  dynamicParameters:
   {{- $params := get $vttabletcc "dynamicParameters" }}
   {{- range $params }}
    - {{ . }}
   {{- end }}
 {{- end}}

      ## define immutable parameter list, this feature is not currently supported.
 {{- if hasKey $vttabletcc "immutableParameters" }}
  immutableParameters:
   {{- $params := get $vttabletcc "immutableParameters" }}
   {{- range $params }}
    - {{ . }}
   {{- end }}
 {{- end}}

  # mysql-scale configuration file format
  fileFormatConfig:
    format: ini
    iniConfig:
      sectionName: vttablet
---
{{- $vtgatecc := .Files.Get "config/mysql-scale-vtgate-config-effect-scope.yaml" | fromYaml }}
apiVersion: apps.kubeblocks.io/v1beta1
kind: ConfigConstraint
metadata:
  name: {{ include "apecloud-mysql.configConstraintVtgateName" . }}
  labels:
    {{- include "apecloud-mysql.labels" . | nindent 4 }}
spec:
  reloadAction:
    autoTrigger:
      processName: vtgate

  parametersSchema:
    topLevelKey: VtGateParameter

    cue: |-
      {{- .Files.Get "config/mysql-scale-vtgate-config-constraint.cue" | nindent 6 }}

  ## define static parameter list
  {{- if hasKey $vtgatecc "staticParameters" }}
  staticParameters:
    {{- $params := get $vtgatecc "staticParameters" }}
    {{- range $params }}
    - {{ . }}
    {{- end }}
  {{- end}}

      ## define dynamic parameter list
  {{- if hasKey $vtgatecc "dynamicParameters" }}
  dynamicParameters:
   {{- $params := get $vtgatecc "dynamicParameters" }}
   {{- range $params }}
    - {{ . }}
   {{- end }}
 {{- end}}

      ## define immutable parameter list, this feature is not currently supported.
 {{- if hasKey $vtgatecc "immutableParameters" }}
  immutableParameters:
   {{- $params := get $vtgatecc "immutableParameters" }}
   {{- range $params }}
    - {{ . }}
   {{- end }}
 {{- end}}

  # mysql-scale configuration file format
  fileFormatConfig:
    format: ini
    iniConfig:
      sectionName: vtgate
