---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apecloud-mysql.configTplVtgateName" . }}
  labels:
    {{- include "apecloud-mysql.labels" . | nindent 4 }}
data:
  vtgate.cnf: |-
    {{- .Files.Get "config/mysql-scale-vtgate-config.tpl" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apecloud-mysql.configTplVttabletName" . }}
  labels:
    {{- include "apecloud-mysql.labels" . | nindent 4 }}
data:
  vttablet.cnf: |-
    {{- .Files.Get "config/mysql-scale-vttablet-config.tpl" | nindent 4 }}
