apiVersion: apps.kubeblocks.io/v1alpha1
kind: ClusterVersion
metadata:
  name: oceanbase-{{ default .Chart.AppVersion .Values.clusterVersionOverride }}
  labels:
    {{- include "oceanbase.labels" . | nindent 4 }}
spec:
  clusterDefinitionRef: oceanbase
  componentVersions:
  - componentDefRef: oceanbase
    versionsContext:
      containers:
      - name: observer-container
        image: {{ .Values.images.registry | default "docker.io" }}/{{ .Values.images.observer.repository }}:{{ .Values.images.observer.tag }}
        imagePullPolicy: {{ default .Values.images.pullPolicy "IfNotPresent" }}
      - name: metrics
        image: {{ .Values.images.registry | default "docker.io" }}/{{ .Values.images.metrics.repository }}:{{ .Values.images.metrics.tag }}
        imagePullPolicy: {{ default .Values.images.pullPolicy "IfNotPresent" }}
  - componentDefRef: oceanbase-hostnetwork
    versionsContext:
      containers:
      - name: observer-container
        image: {{ .Values.images.registry | default "docker.io" }}/{{ .Values.images.observer.repository }}:{{ .Values.images.observer.tag }}
        imagePullPolicy: {{ default .Values.images.pullPolicy "IfNotPresent" }}
      - name: metrics
        image: {{ .Values.images.registry | default "docker.io" }}/{{ .Values.images.metrics.repository }}:{{ .Values.images.metrics.tag }}
        imagePullPolicy: {{ default .Values.images.pullPolicy "IfNotPresent" }}
  - componentDefRef: oceanbase-configserver
    versionsContext:
      containers:
      - name: obconfigserver
        image: oceanbase/ob-configserver:1.0.0-2
        imagePullPolicy: {{ default .Values.images.pullPolicy "IfNotPresent" }}
  - componentDefRef: oceanbase-proxy
    versionsContext:
      containers:
      - name: ob-proxy
        image: oceanbase/obproxy-ce:4.2.1.0-11
        imagePullPolicy: {{ default .Values.images.pullPolicy "IfNotPresent" }}