apiVersion: v1
kind: ConfigMap
metadata:
  name: oceanbase-init-config
  labels:
    {{- include "oceanbase.labels" . | nindent 4 }}
data:
  oceanbase.conf: |-
    {{- .Files.Get "config/oceanbase-init-config.tpl" | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oceanbase-config
  labels:
    {{- include "oceanbase.labels" . | nindent 4 }}
data:
  oceanbase.conf: |-
    {{- .Files.Get "config/oceanbase-config.tpl" | nindent 4 }}
