apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: hive
  namespace: default
  labels:
    helm.sh/chart: hive-cluster-0.9.0
    app.kubernetes.io/version: "3.1.3"
    app.kubernetes.io/instance: hive
spec:
  terminationPolicy: Delete
  clusterDefinitionRef: hive
  topology: hive-cluster
  componentSpecs:
  - name: metastore
    componentDef: hive-metastore
    replicas: 3
    resources:
      requests:
        cpu: '0.5'
        memory: 0.5Gi
      limits:
        cpu: '1'
        memory: 2Gi
    volumes:
      - name: hadoop-core-config
        configMap:
          name: k8shadoop-hadoop-core-config
      - name: hadoop-hdfs-config
        configMap:
          name: k8shadoop-namenode-config
    volumeClaimTemplates:
    - name: metadata
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi