apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: risingwave-cluster
  namespace: default
  annotations:
    # Create the hummock option
    # RW_STATE_STORE: State store url, the hummockConnectionString for minio is: hummock+minio://$(MINIO_USERNAME):$(MINIO_PASSWORD)@${MINIO_ENDPOINT}/${MINIO_BUCKET}
    # RW_DATA_DIRECTORY: Remote directory for storing data and metadata objects.
    # RW_ETCD_ENDPOINTS: Etcd endpoint
    # RW_ETCD_AUTH: Enable authentication with etcd.
    kubeblocks.io/extra-env: '{"RW_STATE_STORE":"hummock+minio://kubeblocks:kubeblocks@kb-addon-minio.kb-system.svc:9000/kbcli-test","RW_DATA_DIRECTORY":"risingwave-cluster","RW_ETCD_ENDPOINTS":"etcdr-cluster-etcd.default.svc.cluster.local:2379","RW_ETCD_AUTH":"false"}'
spec:
  # Specifies the name of the ClusterDefinition to use when creating a Cluster.
  clusterDefinitionRef: risingwave
  # Refers to the ClusterVersion name. Deprecated since v0.9, use ComponentVersion instead. This field is maintained for backward compatibility and its use is discouraged. Existing usage should be updated to the current preferred approach to avoid compatibility issues in future releases.
  clusterVersionRef: risingwave-v1.0.0
  terminationPolicy: Delete
  # Specifies a list of ClusterComponentSpec objects used to define the individual components that make up a Cluster. This field allows for detailed configuration of each component within the Cluster.
  # Note: `shardingSpecs` and `componentSpecs` cannot both be empty; at least one must be defined to configure a cluster.
  # ClusterComponentSpec defines the specifications for a Component in a Cluster.
  componentSpecs:
  - name: frontend
    componentDefRef: frontend
    replicas: 1
    resources:
      limits:
        cpu: '0.5'
        memory: 1Gi
      requests:
        cpu: '0.5'
        memory: 1Gi
  - componentDefRef: meta
    name: meta
    replicas: 1
    resources:
      limits:
        cpu: '0.5'
        memory: 1Gi
      requests:
        cpu: '0.5'
        memory: 1Gi
  - componentDefRef: compute
    name: compute
    replicas: 1
    resources:
      limits:
        cpu: '0.5'
        memory: 1Gi
      requests:
        cpu: '0.5'
        memory: 1Gi
  - componentDefRef: compactor
    name: compactor
    replicas: 1
    resources:
      limits:
        cpu: '0.5'
        memory: 1Gi
      requests:
        cpu: '0.5'
        memory: 1Gi
  - componentDefRef: connector
    name: connector
    replicas: 1
    resources:
      limits:
        cpu: '0.5'
        memory: 1Gi
      requests:
        cpu: '0.5'
        memory: 1Gi
---
apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: etcdr-cluster
  namespace: default
spec:
  clusterDefinitionRef: etcd
  clusterVersionRef: etcd-v3.5.6
  terminationPolicy: WipeOut
  componentSpecs:
    - name: etcd
      componentDefRef: etcd
      disableExporter: true
      replicas: 1
      resources:
        limits:
          cpu: "0.5"
          memory: "0.5Gi"
        requests:
          cpu: "0.5"
          memory: "0.5Gi"
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
