apiVersion: v2
name: wescale
description:

type: application

version: 1.0.0-alpha.0

appVersion: "8.0.30"

home: https://kubeblocks.io/
icon: https://kubeblocks.io/img/logo.png

maintainers:
  - name: xuriwuyun
    url: https://github.com/apecloud/kubeblocks/

sources:
- https://github.com/apecloud/kubeblocks/

annotations:
  addon.kubeblocks.io/kubeblocks-version: ">=0.9.0"
  addon.kubeblocks.io/model: "RDBMS"
  addon.kubeblocks.io/provider: "community"
