apiVersion: v2
description: High Performance, Kubernetes Native Object Storage
name: minio

version: 1.0.0-alpha.0

appVersion: master

# Add a dependency to the kubeblocks definition library chart
dependencies:
  - name: kblib
    version: 0.1.0
    repository: file://../kblib
    alias: extra

keywords:
  - storage
  - object-storage
  - S3

home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
sources:
  - https://github.com/minio/minio

maintainers:
  - name: fengluodb
    url: https://github.com/apecloud/kubeblocks/

annotations:
  addon.kubeblocks.io/kubeblocks-version: ">=1.0.0"
  addon.kubeblocks.io/model: "object-storage"
  addon.kubeblocks.io/provider: "community"