apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gbase-cluster.labels" . | indent 4 }}
spec:
  terminationPolicy: {{ .Values.extra.terminationPolicy }}
  {{- include "kblib.affinity" . | indent 2 }}
  clusterDefinitionRef: gbase
  topology: replication
  componentSpecs:
    {{- include "gbase-cluster.replication.specs" . | indent 4 }}