apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gbase-cluster.labels" . | indent 4 }}
spec:
  terminationPolicy: {{ .Values.extra.terminationPolicy }}
  {{- include "kblib.affinity" . | indent 2 }}
  clusterDefinitionRef: gbase
  {{- if eq .Values.mode "replication" }}
  topology: replication
  componentSpecs:
    {{- include "gbase-cluster.single.specs" . | indent 4 }}
  {{- else }}
  topology: distribution
  shardingSpecs:
  - name: datanode-shard
    shards: 3
    template:
      name: gbase-datanode
      componentDef: gbase-datanode
      replicas: 3
      resources:
        limits:
          cpu: 1000m
          memory:  2Gi
        requests:
          cpu: 1000m
          memory:  2Gi
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
              storage: 20Gi
  
  {{- end }}