apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kblib.clusterName" . }}-ssh-gen-account
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "kblib.clusterName" . }}-secret-creator
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-creator-binding
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1" 
subjects:
- kind: ServiceAccount
  name: {{ include "kblib.clusterName" . }}-ssh-gen-account
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "kblib.clusterName" . }}-secret-creator
  apiGroup: rbac.authorization.k8s.io