apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kblib.clusterName" . }}-create-ssh-secret
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0" 
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ include "kblib.clusterName" . }}-ssh-gen-account
      containers:
      - name: create-ssh-secret
        image: registry.cn-hangzhou.aliyuncs.com/skyrise/gbase_init:amd1.0
        command:
          - /bin/sh
          - -c
          - |
            ssh-keygen -t rsa -b 2048 -f id_rsa -N "" &&
            kubectl delete secret {{ .Values.sshKeySecret }} --namespace {{ .Release.Namespace }} --ignore-not-found &&
            kubectl create secret generic {{ .Values.sshKeySecret }} \
              --from-file=id_rsa=id_rsa \
              --from-file=id_rsa.pub=id_rsa.pub \
              --namespace {{ .Release.Namespace }}
      restartPolicy: Never