# Default values for oceanbase.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  registry: oceanbasedev
  pullPolicy: IfNotPresent
  observer:
    repository: oceanbase-chart
    tag: 4.2.0.0-100010032023083021

roleProbe:
  failureThreshold: 3
  periodSeconds: 2
  timeoutSeconds: 2

nameOverride: ""
fullnameOverride: ""
clusterVersionOverride: "4.2.0.0-100010032023083021"