apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: minio-cluster
  namespace: default
spec:
  terminationPolicy: Delete
  componentSpecs:
  - name: minio
    componentDef: minio
    replicas: 2
    resources:
      limits:
        cpu: '0.5'
        memory: 0.5Gi
      requests:
        cpu: '0.5'
        memory: 0.5Gi
    volumeClaimTemplates:
      - name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi