apiVersion: apps.kubeblocks.io/v1alpha1
kind: ComponentDefinition
metadata:
  name: {{ include "wesql.cmpdNameWeSQLServer" . }}
  labels:
    {{- include "wesql.labels" . | nindent 4 }}
  annotations:
    {{- include "wesql.annotations" . | nindent 4 }}
spec:
  {{- include "wesql.spec.common" . | nindent 2 }}
  configs:
    - name: wesql-server-config
      templateRef: {{ include "wesql.configTplName" . }}
      constraintRef: {{ include "wesql.configConstraintName" . }}
      volumeName: wesql-server-config
      namespace: {{ .Release.Namespace }}
      reRenderResourceTypes:
        - vscale
    - name: vttablet-config
      templateRef: {{ include "wesql.configTplVttabletName" . }}
      constraintRef: {{ include "wesql.configConstraintVttabletName" . }}
      volumeName: wescale-config
      namespace: {{ .Release.Namespace }}
  runtime:
    containers:
      - name: wesql-server
        imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
        command:
          - /bin/sh
          - -c
          - |
            if [[ "$KB_POD_NAME" == *"-0"* ]]; then
              WESQL_LOGGER_MODE="0"
            else
              WESQL_LOGGER_MODE="1"
            fi
            exec docker-entrypoint.sh
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: {{ .Values.auth.password }}
          - name: WESQL_CLUSTER_MEMBER
            value: "$(KB_POD_FQDN)"
          - name: MYSQL_CUSTOM_CONFIG
            value: |
{{ .Values.cluster.customConfig | indent 14 }}
          - name: WESQL_OBJECTSTORE_ACCESS_KEY
            value: {{ .Values.objectStore.accessKey }}
          - name: WESQL_OBJECTSTORE_SECRET_KEY
            value: {{ .Values.objectStore.secretKey }}
        ports:
          - containerPort: 3306
            name: wesql
            protocol: TCP
          - containerPort: 13306
            name: raft
            protocol: TCP
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: wesql
        volumeMounts:
          - mountPath: {{ .Values.mysqlConfigs.dataMountPath }}
            name: data
      - name: vtablet
        {{- include "wesql.spec.runtime.vtablet" . |  nindent 8 }}
      - name: mysql-exporter
        {{- include "wesql.spec.runtime.exporter" . | nindent 8 }}
    volumes:
      {{- include "wesql.spec.runtime.volumes" . | nindent 4 }}
