{{- $cc := .Files.Get "config/wesql-server-config-effect-scope.yaml" | fromYaml }}
apiVersion: apps.kubeblocks.io/v1beta1
kind: ConfigConstraint
metadata:
  name: {{ include "wesql.configConstraintName" . }}
  labels:
    {{- include "wesql.labels" . | nindent 4 }}
spec:
  # configmap reference
  # tplRef: wesql-server-3node-tpl-8.0
  reloadAction:
    tplScriptTrigger:
      sync: true
      scriptConfigMapRef: {{ include "wesql.cmReloadScriptName" .}}
      namespace: {{ .Release.Namespace }}


  # ConfigurationSchema that impose restrictions on engine parameter's rule
  parametersSchema:
    # top level mysql configuration type
    topLevelKey: MysqlParameter

    # schemaInJSON: auto generate from cue scripts
    # example: ../../pkg/configuration/testdata/mysql_openapi.json
    cue: |-
      {{- .Files.Get "config/wesql-server-config-constraint.cue" | nindent 6 }}

  ## define static parameter list
  {{- if hasKey $cc "staticParameters" }}
  staticParameters:
    {{- $params := get $cc "staticParameters" }}
    {{- range $params }}
    - {{ . }}
    {{- end }}
  {{- end}}

  ## define dynamic parameter list
  {{- if hasKey $cc "dynamicParameters" }}
  dynamicParameters:
   {{- $params := get $cc "dynamicParameters" }}
   {{- range $params }}
    - {{ . }}
   {{- end }}
 {{- end}}

 ## define immutable parameter list, this feature is not currently supported.
 {{- if hasKey $cc "immutableParameters" }}
  immutableParameters:
   {{- $params := get $cc "immutableParameters" }}
   {{- range $params }}
    - {{ . }}
   {{- end }}
 {{- end}}


  # mysql configuration file format
  fileFormatConfig:
    format: ini
    iniConfig:
      sectionName: mysqld
---
{{- $vttabletcc := .Files.Get "config/wescale-vttablet-config-effect-scope.yaml" | fromYaml }}
apiVersion: apps.kubeblocks.io/v1beta1
kind: ConfigConstraint
metadata:
  name: {{ include "wesql.configConstraintVttabletName" . }}

  labels:
    {{- include "wesql.labels" . | nindent 4 }}
spec:
  reloadAction:
    autoTrigger:
      processName: vttablet

  parametersSchema:
    topLevelKey: VtTabletParameter
    cue: |-
      {{- .Files.Get "config/wescale-vttablet-config-constraint.cue" | nindent 6 }}

  ## define static parameter list
  {{- if hasKey $vttabletcc "staticParameters" }}
  staticParameters:
    {{- $params := get $vttabletcc "staticParameters" }}
    {{- range $params }}
    - {{ . }}
    {{- end }}
  {{- end}}

      ## define dynamic parameter list
  {{- if hasKey $vttabletcc "dynamicParameters" }}
  dynamicParameters:
   {{- $params := get $vttabletcc "dynamicParameters" }}
   {{- range $params }}
    - {{ . }}
   {{- end }}
 {{- end}}

      ## define immutable parameter list, this feature is not currently supported.
 {{- if hasKey $vttabletcc "immutableParameters" }}
  immutableParameters:
   {{- $params := get $vttabletcc "immutableParameters" }}
   {{- range $params }}
    - {{ . }}
   {{- end }}
 {{- end}}

  # wescale configuration file format
  fileFormatConfig:
    format: ini
    iniConfig:
      sectionName: vttablet
---
{{- $vtgatecc := .Files.Get "config/wescale-vtgate-config-effect-scope.yaml" | fromYaml }}
apiVersion: apps.kubeblocks.io/v1beta1
kind: ConfigConstraint
metadata:
  name: {{ include "wesql.configConstraintVtgateName" . }}
  labels:
    {{- include "wesql.labels" . | nindent 4 }}
spec:
  reloadAction:
    autoTrigger:
      processName: vtgate

  parametersSchema:
    topLevelKey: VtGateParameter

    cue: |-
      {{- .Files.Get "config/wescale-vtgate-config-constraint.cue" | nindent 6 }}

  ## define static parameter list
  {{- if hasKey $vtgatecc "staticParameters" }}
  staticParameters:
    {{- $params := get $vtgatecc "staticParameters" }}
    {{- range $params }}
    - {{ . }}
    {{- end }}
  {{- end}}

      ## define dynamic parameter list
  {{- if hasKey $vtgatecc "dynamicParameters" }}
  dynamicParameters:
   {{- $params := get $vtgatecc "dynamicParameters" }}
   {{- range $params }}
    - {{ . }}
   {{- end }}
 {{- end}}

      ## define immutable parameter list, this feature is not currently supported.
 {{- if hasKey $vtgatecc "immutableParameters" }}
  immutableParameters:
   {{- $params := get $vtgatecc "immutableParameters" }}
   {{- range $params }}
    - {{ . }}
   {{- end }}
 {{- end}}

  # wescale configuration file format
  fileFormatConfig:
    format: ini
    iniConfig:
      sectionName: vtgate