apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: {{ include "kblib.clusterName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "kblib.clusterLabels" . | nindent 4 }}
spec:
  terminationPolicy: {{ .Values.extra.terminationPolicy }}
  {{ include "kblib.affinity" . | indent 2 }}
  componentSpecs:
    - componentDef: minio 
      name: minio
      replicas: {{ .Values.replicas }}
      env:
      - name: MINIO_BUCKETS
        value: {{ .Values.buckets }}
      {{- if .Values.user }}
      - name: MINIO_ROOT_USER
        value: {{ .Values.user }}
      {{- end }}
      {{- if .Values.password }}
      - name: MINIO_ROOT_PASSWORD
        value: {{ .Values.password }}
      {{- end }}
      serviceAccountName: {{ include "kblib.serviceAccountName" . }}
      {{- include "kblib.componentMonitor" . | indent 6 }}
      {{- include "kblib.componentResources" . | indent 6 }}
      {{- include "kblib.componentStorages" . | indent 6 }}