name: Release Version

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'The version of release'
        required: true
        default: ''
      release_branch:
        description: 'The branch of release'
        required: true
        default: 'main'

run-name: ref_name:${{ inputs.release_branch }} release_version:${{ inputs.release_version }}

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  release-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch ${{ inputs.release_branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.release_branch }}

      - name: push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{ inputs.release_version }}
          github_token: ${{ env.GITHUB_TOKEN }}
          tag_prefix: ""
