# Default values for redis-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# if useLegacyCompDef is false ,cluster will be rendered by compDef rather than componentDefRef in cluster definition
useLegacyCompDef: true


## @param version redis cluster version
##
version: redis-7.0.6

## @param mode redis cluster topology mode, standalone, replication and cluster
## standalone: single redis instance
## replication: primary-secondary replication with redis sentinel, refer: https://redis.io/docs/management/sentinel
## cluster: official redis cluster, refer: https://redis.io/docs/reference/cluster-spec. if mode is cluster, please set useLegacyCompDef to false.
mode: replication

## @param replicas specify replicas of replication
## if mode is standalone, replicas should be 1
## if mode is replication and replicas is 2, it means 1 primary and 1 secondary
## if mode is cluster and replicas is 2, it means every shard has 1 primary and 1 secondary, the count of shards is specified by redisCluster.shardCount
replicas: 2

## @param shards if mode is cluster, specify the redis cluster shard count, the minimum value is 3
shards: 3

## @param cpu
##
cpu: 0.5

## @param memory, the unit is Gi
##
memory: 0.5

## @param requests.cpu if not set, use cpu
## @param requests.memory, if not set, use memory
##
requests:
#  cpu:
#  memory:

## @param storage size, the unit is Gi
##
storage: 20

## @param twemproxy.enable
## @param sentinel.cpu
## @param sentinel.memory
## @param sentinel.replicas
##
twemproxy:
  enabled: false
  replicas: 3
  cpu: 0.2
  memory: 0.2

## @param nodePortEnabled
nodePortEnabled: false

## @param sentinel.cpu
## @param sentinel.memory
## @param sentinel.storage
##
sentinel:
  enabled: true
  cpu: 0.2
  memory: 0.2
  storage: 20
  replicas: 3
